#!/usr/bin/env bash
# installing and config nginx

apt-get update
apt-get -y install nginx
# adding a html page
echo "Hello World!" > /var/www/html/index.html
# checking if service is running
pids=$(pgrep nginx)
if [ -n "$pids" ];
then
	service nginx start
else
	service nginx restart
fi
