#!/usr/bin/env bash
# installing and config Ngnix

apt-get update
apt-get -y install ngnix
# adding a html page
echo "Hello World!" > /var/www/html/index.html
# checking if service is running
pids=$(pgrep ngnix)
if [ -n "$pids" ];
then
	service ngnix start
else
	service nginx restart
fi
