#!/usr/bin/env bash
# installing and config nginx

apt-get update
apt-get -y install nginx

# adding a html page
echo "Hello World!" > /var/www/html/index.html

redirection="\n\t location /redirect_me {\n\t\treturn 301 http://www.google.com$request_uri;\n\t }"

sudo sed -i "/server_name/a \ $redirection" /etc/nginx/sites-available/default

# checking if service is running
state=$(pgrep nginx)
if [ -n "$state" ];
then
	sudo service nginx start
else
	sudo service nginx restart
fi
echo "done"
