#!/usr/bin/env bash
#display user and id
while IFS=':' read -r username _ userid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $home"
done < /etc/passwd

