#!/usr/bin/env bash
# fixing the apache2 server config

sudo apt-get update
sudo apt-get install apache2
sudo cd /etc/apache2/
sudo echo "ServerName 127.17.0.2" >> apache2.conf
sudo service apache2 start
